### ISSUE TITLE
[Style fixes] Intro modal

### ISSUE THREAD

**Issue by jasperjansz** [blockstack/connect#45]
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/f4dfcfaf-2687-4d24-88d2-fbc076708dd8)

- [x] 1. Remove Secret Key logo: fixed in https://github.com/blockstack/connect/pull/49
- [ ] 2. ~~Update header font:~~ tracked here -> https://github.com/blockstack/ui/issues/34
- [x] 2.a. It should also be 20px instead of 24px (Header small): fixed in https://github.com/blockstack/connect/pull/49
- [ ] 3. ~~font size for button label should be 14px (body medium)~~ tracked here -> https://github.com/blockstack/ui/issues/36
- [x] 4. Footer links should be 12px (caption medium): fixed in https://github.com/blockstack/connect/pull/49
- [ ] 5. ~~Modal width should be 396px instead of 440px~~: tracked here -> https://github.com/blockstack/ui/issues/35
- [x] 6. padding left and right should be 32px instead of 24px (not applicable to close icon): fixed in https://github.com/blockstack/connect/pull/49
- [ ] 7. The header text should be subject to the same padding. That's 24px (always) on mobile specifically:
![image.png](https://images.zenhubusercontent.com/5c7593d7f4e4f4273dcf4b86/2a3fd55f-acc9-4680-8484-5f23b1a9b689)
